### ISSUE TITLE
Calling .last on an empty model will cause a datatype mismatch error

### ISSUE THREAD

**Issue by sajoku** [infinitered/cdq#104]
I upgraded cdq to 1.0.3 and am using `.last` to get a specific object. But doing so on an empty array of object crashes my app. 

Trace:

```
(main)> BluetoothDevice.all.last
2015-06-23 07:51:38.071 Bmm[61537:721034] CoreData: error: (20) datatype mismatch
2015-06-23 07:51:38.072 Bmm[61537:721034] Core Data: error: -executeRequest: encountered exception = error during SQL execution : datatype mismatch with userInfo = {
    NSFilePath = "/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite";
    NSSQLiteErrorDomain = 20;
}
2015-06-23 07:51:38.072 Bmm[61537:721034] CoreData: error: (20) datatype mismatch
2015-06-23 07:51:38.073 Bmm[61537:721034] Core Data: error: -executeRequest: encountered exception = error during SQL execution : datatype mismatch with userInfo = {
    NSFilePath = "/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite";
    NSSQLiteErrorDomain = 20;
}
2015-06-23 07:51:38.084 Bmm[61537:721034] CoreData: error: (20) datatype mismatch
2015-06-23 07:51:38.085 Bmm[61537:721034] Core Data: error: -executeRequest: encountered exception = error during SQL execution : datatype mismatch with userInfo = {
    NSFilePath = "/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite";
    NSSQLiteErrorDomain = 20;
}
2015-06-23 07:51:38.093 Bmm[61537:721034] CoreData: error: (20) datatype mismatch
"Error Domain=NSCocoaErrorDomain Code=20 \"The operation couldn’t be completed. (Cocoa error 20.)\" UserInfo=0x10cba1ad0 {NSFilePath=/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite, NSSQLiteErrorDomain=20, NSUnderlyingException=error during SQL execution : datatype mismatch}"
2015-06-23 07:51:38.116 Bmm[61537:721034] object.rb:61:in `with_error_object:': Error while fetching: Error Domain=NSCocoaErrorDomain Code=20 "The operation couldn‚Äö√Ñ√¥t be completed. (Cocoa error 20.)" UserInfo=0x10cba1ad0 {NSFilePath=/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite, NSSQLiteErrorDomain=20, NSUnderlyingException=error during SQL execution : datatype mismatch} (RuntimeError)
        from targeted_query.rb:48:in `array'
        from targeted_query.rb:75:in `last:'
=> #<RuntimeError: Error while fetching: Error Domain=NSCocoaErrorDomain Code=20 "The operation couldn’t be completed. (Cocoa error 20.)" UserInfo=0x10cba1ad0 {NSFilePath=/Users/sajoku/Library/Developer/CoreSimulator/Devices/40879C76-CADB-460F-B2AD-398A72B71077/data/Containers/Data/Application/D5C80D82-5E31-484F-81AD-A15547348477/Documents/ios.sqlite, NSSQLiteErrorDomain=20, NSUnderlyingException=error during SQL execution : datatype mismatch}>
```

I guess this piece of code in targeted_query.rb causes problems:

``` ruby
    # Return the last entity matching the query.
    #
    # Causes execution.
    #
    def last(n = 1)
      result = offset(count - n).limit(n).array
      n == 1 ? result.first : result
    end
```

You can reproduce the problem with the following spec in targeted_query_spec.rb:
(mainly just a copy-paste of an existing one).

``` ruby
it "returns nil if no last entry is present" do
      CDQ.cdq.reset!
      @tq.sort_by(:name).last.should == nil
    end
```

But I'm not sure how to go about a fix for this and not cause any problems for other people :)

**Comment by kemiller** [comment]
Easiest is probably just to return nil if count == 0.  Send me a patch and I'll merge it ;)

**Comment by sajoku** [comment]
I'm not using cdq anymore myself and don't intend to create a pr for this mainly because there doesn't seem to be any other person having this problem 🙂 
I'll close this issues for the sake of keeping a clean(er) project.
