### ISSUE TITLE
Including CDQ in a motion-game template?

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/cdq#128]
there is a way to include CDQ in a motion-game template?

I try:

```
class Application < MG::Application
  include CDQ  
  
  def start
    cdq.setup
    MG::Director.shared.run(MenuScene.new)
  end
end
```
and

```
class Score < CDQManagedObject
end  
```

but i get:
```
*** Starting simulator
(main)> 2016-02-29 15:58:49.832 Hubble[38952:1824353] score.rb:1:in `<main>': uninitialized constant CDQManagedObject (NameError)
2016-02-29 15:58:49.835 Hubble[38952:1824353] *** Terminating app due to uncaught exception 'NameError', reason: 'score.rb:1:in `<main>': uninitialized constant CDQManagedObject (NameError)
```

Any idea?

**Comment by kemiller** [comment]
There should be nothing special about it AFAIK but I have no experience with motion-game.  Seems like a more general compilation order issue.
