### ISSUE TITLE
Can't find model for source store

### ISSUE THREAD

**Issue by andersennl** [infinitered/cdq#97]
I've followed this tutorial [RedPotion docs](http://redpotion.readthedocs.org/en/latest/cookbook/core_data/) to set up the initial migration file. After starting the simulator, the app crashes on startup. I'm not entirely sure where the error is. Thanks for your help! This is the error:
```
(main)> 2015-05-18 17:09:52.088 myapp2[94303:14320802] CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/nandersen/Library/Developer/CoreSimulator/Devices/BFD4E377-FBC5-4C8B-BEC8-502619238C50/data/Containers/Data/Application/938F5D4A-2EF8-4156-B74E-60FBE852FBC7/Documents/myapp2.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=NSCocoaErrorDomain Code=134130 "The operation couldn’t be completed. (Cocoa error 134130.)" UserInfo=0x10bfec320 {URL=file:///Users/nandersen/Library/Developer/CoreSimulator/Devices/BFD4E377-FBC5-4C8B-BEC8-502619238C50/data/Containers/Data/Application/938F5D4A-2EF8-4156-B74E-60FBE852FBC7/Documents/myapp2.sqlite, metadata={
    NSPersistenceFrameworkVersion = 519;
    NSStoreModelVersionHashes =     {
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        "0001 initial"
    );
    NSStoreType = SQLite;
    NSStoreUUID = "B3FF13B6-B495-41CA-926A-2A41595A2FC3";
    "_NSAutoVacuumLevel" = 2;
}, reason=Can't find model for source store} with userInfo dictionary {
    URL = "file:///Users/nandersen/Library/Developer/CoreSimulator/Devices/BFD4E377-FBC5-4C8B-BEC8-502619238C50/data/Containers/Data/Application/938F5D4A-2EF8-4156-B74E-60FBE852FBC7/Documents/myapp2.sqlite";
    metadata =     {
        NSPersistenceFrameworkVersion = 519;
        NSStoreModelVersionHashes =         {
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            "0001 initial"
        );
        NSStoreType = SQLite;
        NSStoreUUID = "B3FF13B6-B495-41CA-926A-2A41595A2FC3";
        "_NSAutoVacuumLevel" = 2;
    };
    reason = "Can't find model for source store";
}
2015-05-18 17:09:52.089 myapp2[94303:14320802] CoreData: annotation: NSPersistentStoreCoordinator's current model hashes are {
    Food = <ada04fd0 bc0d99ba e7eacf3c 3e9ce26e 03aa73fd aab6f1be 76f59a15 9f97bbf9>;
    User = <67d1f66f 600315f1 b040750b 6e069e68 d818f026 a0c8ca36 8c447941 9fdbbf7b>;
}
2015-05-18 17:09:52.089 myapp2[94303:14320802] NSStoreUUID: B3FF13B6-B495-41CA-926A-2A41595A2FC3
2015-05-18 17:09:52.089 myapp2[94303:14320802] NSStoreModelVersionIdentifiers: ["0001 initial"]
2015-05-18 17:09:52.089 myapp2[94303:14320802] NSStoreType: SQLite
2015-05-18 17:09:52.090 myapp2[94303:14320802] _NSAutoVacuumLevel: 2
2015-05-18 17:09:52.090 myapp2[94303:14320802] NSStoreModelVersionHashes: {}
2015-05-18 17:09:52.090 myapp2[94303:14320802] NSPersistenceFrameworkVersion: 519
2015-05-18 17:09:52.090 myapp2[94303:14320802] NSStoreModelVersionHashesVersion: 3
2015-05-18 17:09:52.168 myapp2[94303:14320802] store.rb:122:in `create_local_store': Can't find model for source store (RuntimeError)
	from store.rb:43:in `create_store'
	from store.rb:23:in `current'
	from context.rb:123:in `block in create:'
	from context.rb:127:in `create:'
	from context.rb:27:in `push:'
	from object.rb:36:in `setup:'
	from app_delegate.rb:7:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-05-18 17:09:52.169 myapp2[94303:14320802] store.rb:122:in `create_local_store': Can't find model for source store (RuntimeError)
	from store.rb:43:in `create_store'
	from store.rb:23:in `current'
	from context.rb:123:in `block in create:'
	from context.rb:127:in `create:'
	from context.rb:27:in `push:'
	from object.rb:36:in `setup:'
	from app_delegate.rb:7:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-05-18 17:09:52.175 myapp2[94303:14320802] *** Terminating app due to uncaught exception 'RuntimeError', reason: 'store.rb:122:in `create_local_store': Can't find model for source store (RuntimeError)
	from store.rb:43:in `create_store'
	from store.rb:23:in `current'
	from context.rb:123:in `block in create:'
	from context.rb:127:in `create:'
	from context.rb:27:in `push:'
	from object.rb:36:in `setup:'
	from app_delegate.rb:7:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102f2ac65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001008c5bb7 objc_exception_throw + 45
	2   myapp2                            0x00000001003ea9df _ZL10__vm_raisev + 399
	3   myapp2                            0x00000001003eab0d rb_vm_raise + 205
	4   myapp2                            0x00000001002e8625 rb_f_raise + 69
	5   myapp2                            0x00000001003bbcd5 rb_vm_dispatch + 5925
	6   myapp2                            0x0000000100041cbc vm_dispatch + 1436
	7   myapp2                            0x00000001000f62e2 rb_scope__create_local_store__ + 2738
	8   myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	9   myapp2                            0x0000000100041cbc vm_dispatch + 1436
	10  myapp2                            0x00000001000f3c9d rb_scope__create_store__ + 349
	11  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	12  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	13  myapp2                            0x00000001000f3853 rb_scope__current__ + 99
	14  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	15  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	16  myapp2                            0x00000001000e3384 rb_scope__create:__block__ + 132
	17  myapp2                            0x00000001003bd54f _ZL13vm_block_evalP7RoxorVMP11rb_vm_blockP13objc_selectormiPKm + 1119
	18  myapp2                            0x00000001000eaedc __unnamed_414 + 44
	19  CoreData                            0x0000000100e2ba79 developerSubmittedBlockToNSManagedObjectContextPerform + 201
	20  CoreData                            0x0000000100e2b951 -[NSManagedObjectContext performBlockAndWait:] + 257
	21  myapp2                            0x00000001000eaea4 __unnamed_347 + 132
	22  myapp2                            0x00000001003bbe2e rb_vm_dispatch + 6270
	23  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	24  myapp2                            0x00000001000e3235 rb_scope__create:__ + 3333
	25  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	26  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	27  myapp2                            0x00000001000e18c2 rb_scope__push:__ + 402
	28  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	29  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	30  myapp2                            0x00000001000fa82c rb_scope__setup:__ + 476
	31  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	32  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	33  myapp2                            0x00000001002a1e33 rb_scope__on_load:__ + 163
	34  myapp2                            0x00000001003bc299 rb_vm_dispatch + 7401
	35  myapp2                            0x0000000100041cbc vm_dispatch + 1436
	36  myapp2                            0x000000010021dfea rb_scope__application:didFinishLaunchingWithOptions:__ + 202
	37  myapp2                            0x000000010021e1ed __unnamed_34 + 61
	38  UIKit                               0x0000000101b1d788 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
	39  UIKit                               0x0000000101b1e397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
	40  UIKit                               0x0000000101b211de -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	41  UIKit                               0x0000000101b200d5 -[UIApplication workspaceDidEndTransaction:] + 179
	42  FrontBoardServices                  0x0000000105f3a5e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	43  CoreFoundation                      0x0000000102e5e41c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	44  CoreFoundation                      0x0000000102e54165 __CFRunLoopDoBlocks + 341
	45  CoreFoundation                      0x0000000102e53f25 __CFRunLoopRun + 2389
	46  CoreFoundation                      0x0000000102e53366 CFRunLoopRunSpecific + 470
	47  UIKit                               0x0000000101b1fb42 -[UIApplication _run] + 413
	48  UIKit                               0x0000000101b22900 UIApplicationMain + 1282
	49  myapp2                            0x000000010004a02f main + 111
	50  libdyld.dylib                       0x0000000104936145 start + 1
	51  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type RuntimeError
```

This is my `0001_initial.rb`:
```ruby
schema "0001 initial" do
  entity "User" do
    string :name, optional: false
    integer32 :fcc, optional: false
    integer32 :finetuning
    string :unit
    string :unittype
    string :intaketype
  end

  entity "Food" do
    string :name, optional: false
    integer32 :fcc, optional: false
    string :note

    datetime :created_at
    datetime :updated_at
  end
end
```

This is my `app_delegate.rb`:
```ruby
class AppDelegate < PM::Delegate
  include CDQ

  status_bar true, animation: :fade

  def on_load(app, options)
    cdq.setup
  end
  ...
end
```

**Comment by willrax** [comment]
Hey. Silly question, I know. Have you tried resetting the simulator?

**Comment by andersennl** [comment]
No stupid question at all. I totally forgot to delete the app from the simulator and try again. Worked perfectly. Thanks a lot! 👍

**Comment by willrax** [comment]
I only ask because I've been stung by this so many times. :) Glad you got it sorted,
